<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            "Electrónica",
            "Moda",
            "Salud y Belleza",
            "Hogar y Jardín",
            "Deportes y Aire Libre",
            "Automóviles",
            "Viajes",
            "Restaurantes",
            "Entretenimiento",
            "Tecnología",
            "Educación",
            "Juguetes",
            "Libros",
            "Música",
            "Cine",
            "Fotografía",
            "Computadoras",
            "Teléfonos Móviles",
            "Electrodomésticos",
            "Muebles",
            "Decoración del Hogar",
            "Fitness",
            "Ropa de Trabajo",
            "Ropa de Niños",
            "Accesorios de Moda",
            "Joyería",
            "Cosméticos",
            "Productos Naturales",
            "Artículos para Mascotas",
            "Oficinas y Papelería",
            "Instrumentos Musicales",
            "Cámaras",
            "Videojuegos",
            "Software",
            "Entradas para Eventos",
            "Cursos Online",
            "Entrenamiento Personal",
            "Repuestos de Automóviles",
            "Suministros de Jardinería",
            "Ropa de Verano",
            "Ropa de Invierno",
            "Calzado",
            "Bolsos",
            "Relojes",
            "Lentes de Sol",
            "Productos de Cocina",
            "Artículos para el Hogar",
            "Herramientas",
            "Material de Construcción",
            "Electrodomésticos de Cocina",
            "Suplementos Alimenticios",
            "Vinos y Bebidas",
            "Productos de Panadería",
            "Alimentos Gourmet",
            "Servicios de Belleza",
            "Paquetes de Vacaciones",
            "Escapadas de Fin de Semana",
            "Circuitos Turísticos",
            "Alquiler de Vehículos",
            "Tours Guiados",
            "Entradas para Parques Temáticos",
            "Restaurantes de Lujo",
            "Bares y Cafés",
            "Aplicaciones Móviles",
            "Accesorios para Automóviles",
            "Cuidado de la Piel",
            "Productos para el Cabello",
            "Material de Arte",
            "Decoración de Interiores",
            "Artículos para Eventos",
            "Juguetes Educativos",
            "Ropa Casual",
            "Ropa Deportiva",
            "Equipos de Deporte",
            "Equipos de Camping",
            "Servicios de Lavandería",
            "Entrenadores Personales",
            "Estudios de Fotografía",
            "Viajes en Crucero",
            "Alojamientos",
            "Estudios de Yoga",
            "Productos para Bebés",
            "Servicios de Traducción",
            "Asesoramiento Financiero",
            "Servicios de Marketing",
            "Software de Productividad",
            "Herramientas de Oficina",
            "Material Escolar",
            "Suscripciones a Revistas",
            "Entradas para Conciertos",
            "Talleres de Cocina",
            "Ropa de Noche",
            "Accesorios para el Hogar",
            "Vestuarios para Eventos",
            "Servicio de Entrega a Domicilio",
            "Productos de Limpieza",
            "Cursos de Idiomas",
            "Actividades Recreativas",
            "Artículos de Colección",
            "Servicios de Consultoría",
            "Actividades al Aire Libre"
        ];
        
        DB::table('categories')->insert($categories);
    }
}
