<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $types = [
            "Restaurantes",
            "Cafés",
            "Bares",
            "Tiendas de Ropa",
            "Zapaterías",
            "Joyerías",
            "Tiendas de Electrónica",
            "Librerías",
            "Tiendas de Deportes",
            "Tiendas de Belleza",
            "Farmacias",
            "Supermercados",
            "Tiendas de Muebles",
            "Tiendas de Decoración",
            "Centros de Fitness",
            "Clínicas Dentales",
            "Salones de Belleza",
            "Spa",
            "Tiendas de Productos Naturales",
            "Tiendas de Mascotas",
            "Talleres de Automóviles",
            "Agencias de Viajes",
            "Hoteles",
            "Alquiler de Vehículos",
            "Restaurantes de Comida Rápida",
            "Panaderías",
            "Pastelerías",
            "Tiendas de Herramientas",
            "Tiendas de Cocina",
            "Estaciones de Servicio",
            "Centros de Salud",
            "Escuelas de Idiomas",
            "Guarderías",
            "Agencias de Marketing",
            "Estudios Fotográficos",
            "Empresas de Eventos",
            "Centros de Yoga",
            "Escuelas de Arte",
            "Talleres de Reparación Electrónica",
            "Tiendas de Ropa Infantil",
            "Tiendas de Ropa de Trabajo",
            "Empresas de Construcción",
            "Material Escolar",
            "Tiendas de Juegos de Video",
            "Centros de Entrenamiento Personal",
            "Tiendas de Artesanía",
            "Centros de Rehabilitación",
            "Comida Gourmet",
            "Restaurantes de Cocina Internacional",
            "Tiendas de Ropa Vintage",
            "Centros de Belleza y Estética",
            "Centros de Formación Profesional",
            "Academias de Música",
            "Empresas de Consultoría",
            "Proveedores de Servicios Financieros",
            "Estudio de Diseño Gráfico",
            "Tiendas de Ropa Deportiva",
            "Centros de Educación Infantil",
            "Tiendas de Electrónica de Consumo",
            "Talleres de Manualidades",
            "Empresas de Catering",
            "Agencias de Seguros",
            "Empresas de Traducción",
            "Clínicas Veterinarias",
            "Tiendas de Moda Sostenible",
            "Centros de Terapia Física",
            "Tiendas de Productos Ecológicos",
            "Empresas de Limpieza",
            "Comida para Llevar",
            "Clubes de Ocio",
            "Servicios de Entrega",
            "Tiendas de Equipos de Camping",
            "Centros de Atención a la Tercera Edad",
            "Consultorías en TI",
            "Tiendas de Accesorios para Mascotas",
            "Empresas de Organización de Eventos",
            "Centros de Rehabilitación Psicológica",
            "Tiendas de Música",
            "Consultorías en Negocios",
            "Agencias de Publicidad Digital",
            "Empresas de Gestión de Redes Sociales",
            "Tiendas de Productos de Cocina",
            "Empresas de Desarrollo Web",
            "Servicios de Instalación de Electrodomésticos",
            "Escuelas de Cocina",
            "Empresas de Mantenimiento",
            "Tiendas de Juguetes Educativos",
            "Centros de Asesoría Financiera",
            "Servicios de Entrenamiento Empresarial",
            "Agencias de Reclutamiento",
            "Empresas de Outsourcing",
            "Tiendas de Mobiliario para Oficina",
            "Centros de Atención Psicológica",
            "Servicios de Organización de Viajes",
            "Empresas de Gestión de Eventos",
            "Tiendas de Alimentos Orgánicos",
            "Consultorías en Marketing Digital",
            "Servicios de Desarrolladores Freelance",
            "Empresas de Soluciones Tecnológicas",
            "Tiendas de Material de Construcción",
            "Escuelas de Música",
            "Servicios de Revisión de Documentos",
            "Talleres de Fotografía",
            "Empresas de Transporte de Mercancías",
            "Servicios de Reparación de Electrodomésticos",
            "Tiendas de Ropa para Deportes Extremos",
            "Empresas de Planificación Financiera",
            "Centros de Enseñanza en Línea",
            "Servicios de Desarrollo de Aplicaciones",
            "Agencias de Diseño Web",
            "Servicios de Capacitación en TI",
            "Tiendas de Ropa de Temporada",
            "Empresas de Producción de Videos",
            "Talleres de Escultura",
            "Centros de Formación en Habilidades Blandas",
            "Tiendas de Ropa de Alta Costura",
            "Empresas de Renovación de Oficinas",
            "Servicios de Gestión de Proyectos Digitales",
            "Escuelas de Deportes",
            "Tiendas de Equipos de Seguridad",
            "Empresas de Consultoría en Gestión",
            "Servicios de Marketing para Redes Sociales",
            "Tiendas de Productos de Belleza Natural",
            "Empresas de Asesoría Jurídica",
            "Talleres de Fotografía Profesional",
            "Tiendas de Juegos de Mesa",
            "Empresas de Desarrollo de Aplicaciones Móviles",
            "Servicios de Edición de Fotos",
            "Consultorías en Estrategia de Negocios",
            "Tiendas de Ropa para Eventos Especiales",
            "Centros de Investigación y Desarrollo",
            "Servicios de Instalación de Redes",
            "Tiendas de Artículos de Oficina",
            "Empresas de Servicios de TI",
            "Talleres de Pintura",
            "Servicios de Gestión de Contenidos",
            "Tiendas de Productos para el Cuidado del Cabello",
            "Consultorías en Tecnología",
            "Empresas de Eventos Corporativos",
            "Servicios de Diseño de Logos",
            "Tiendas de Decoración Temática",
            "Talleres de Artes Marciales",
            "Tiendas de Equipos de Audio",
            "Servicios de Gestión de Redes Sociales",
            "Empresas de Auditoría",
            "Tiendas de Material de Arte",
            "Servicios de Diseño Editorial",
            "Consultorías en Innovación",
            "Empresas de Servicios de Consultoría",
            "Tiendas de Artículos de Regalo",
            "Servicios de Traducción Técnica",
            "Talleres de Creación de Contenidos",
            "Tiendas de Productos para el Hogar Inteligente",
            "Servicios de Gestión de Campañas Publicitarias",
            "Empresas de Consultoría en Recursos Humanos",
            "Tiendas de Artículos de Cocina Gourmet",
            "Servicios de Fotografía Corporativa",
            "Empresas de Desarrollo de Juegos",
            "Talleres de Escritura Creativa",
            "Tiendas de Accesorios para Deportes",
            "Servicios de Instalación de Software",
            "Consultorías en Estrategia Digital",
            "Tiendas de Productos de Limpieza",
            "Servicios de Organización de Espacios",
            "Talleres de Diseño de Interiores",
            "Tiendas de Productos para el Bienestar"
        ];
        
        DB::table('types')->insert($types);
    }
}
