<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $types = [
            ['name' => "Restaurantes"],
            ['name' => "Cafés"],
            ['name' => "Bares"],
            ['name' => "Tiendas de Ropa"],
            ['name' => "Zapaterías"],
            ['name' => "Joyerías"],
            ['name' => "Tiendas de Electrónica"],
            ['name' => "Librerías"],
            ['name' => "Tiendas de Deportes"],
            ['name' => "Tiendas de Belleza"],
            ['name' => "Farmacias"],
            ['name' => "Supermercados"],
            ['name' => "Tiendas de Muebles"],
            ['name' => "Tiendas de Decoración"],
            ['name' => "Centros de Fitness"],
            ['name' => "Clínicas Dentales"],
            ['name' => "Salones de Belleza"],
            ['name' => "Spa"],
            ['name' => "Tiendas de Productos Naturales"],
            ['name' => "Tiendas de Mascotas"],
            ['name' => "Talleres de Automóviles"],
            ['name' => "Agencias de Viajes"],
            ['name' => "Hoteles"],
            ['name' => "Alquiler de Vehículos"],
            ['name' => "Restaurantes de Comida Rápida"],
            ['name' => "Panaderías"],
            ['name' => "Pastelerías"],
            ['name' => "Tiendas de Herramientas"],
            ['name' => "Tiendas de Cocina"],
            ['name' => "Estaciones de Servicio"],
            ['name' => "Centros de Salud"],
            ['name' => "Escuelas de Idiomas"],
            ['name' => "Guarderías"],
            ['name' => "Agencias de Marketing"],
            ['name' => "Estudios Fotográficos"],
            ['name' => "Empresas de Eventos"],
            ['name' => "Centros de Yoga"],
            ['name' => "Escuelas de Arte"],
            ['name' => "Talleres de Reparación Electrónica"],
            ['name' => "Tiendas de Ropa Infantil"],
            ['name' => "Tiendas de Ropa de Trabajo"],
            ['name' => "Empresas de Construcción"],
            ['name' => "Material Escolar"],
            ['name' => "Tiendas de Juegos de Video"],
            ['name' => "Centros de Entrenamiento Personal"],
            ['name' => "Tiendas de Artesanía"],
            ['name' => "Centros de Rehabilitación"],
            ['name' => "Comida Gourmet"],
            ['name' => "Restaurantes de Cocina Internacional"],
            ['name' => "Tiendas de Ropa Vintage"],
            ['name' => "Centros de Belleza y Estética"],
            ['name' => "Centros de Formación Profesional"],
            ['name' => "Academias de Música"],
            ['name' => "Empresas de Consultoría"],
            ['name' => "Proveedores de Servicios Financieros"],
            ['name' => "Estudio de Diseño Gráfico"],
            ['name' => "Tiendas de Ropa Deportiva"],
            ['name' => "Centros de Educación Infantil"],
            ['name' => "Tiendas de Electrónica de Consumo"],
            ['name' => "Talleres de Manualidades"],
            ['name' => "Empresas de Catering"],
            ['name' => "Agencias de Seguros"],
            ['name' => "Empresas de Traducción"],
            ['name' => "Clínicas Veterinarias"],
            ['name' => "Tiendas de Moda Sostenible"],
            ['name' => "Centros de Terapia Física"],
            ['name' => "Tiendas de Productos Ecológicos"],
            ['name' => "Empresas de Limpieza"],
            ['name' => "Comida para Llevar"],
            ['name' => "Clubes de Ocio"],
            ['name' => "Servicios de Entrega"],
            ['name' => "Tiendas de Equipos de Camping"],
            ['name' => "Centros de Atención a la Tercera Edad"],
            ['name' => "Consultorías en TI"],
            ['name' => "Tiendas de Accesorios para Mascotas"],
            ['name' => "Empresas de Organización de Eventos"],
            ['name' => "Centros de Rehabilitación Psicológica"],
            ['name' => "Tiendas de Música"],
            ['name' => "Consultorías en Negocios"],
            ['name' => "Agencias de Publicidad Digital"],
            ['name' => "Empresas de Gestión de Redes Sociales"],
            ['name' => "Tiendas de Productos de Cocina"],
            ['name' => "Empresas de Desarrollo Web"],
            ['name' => "Servicios de Instalación de Electrodomésticos"],
            ['name' => "Escuelas de Cocina"],
            ['name' => "Empresas de Mantenimiento"],
            ['name' => "Tiendas de Juguetes Educativos"],
            ['name' => "Centros de Asesoría Financiera"],
            ['name' => "Servicios de Entrenamiento Empresarial"],
            ['name' => "Agencias de Reclutamiento"],
            ['name' => "Empresas de Outsourcing"],
            ['name' => "Tiendas de Mobiliario para Oficina"],
            ['name' => "Centros de Atención Psicológica"],
            ['name' => "Servicios de Organización de Viajes"],
            ['name' => "Empresas de Gestión de Eventos"],
            ['name' => "Tiendas de Alimentos Orgánicos"],
            ['name' => "Consultorías en Marketing Digital"],
            ['name' => "Servicios de Desarrolladores Freelance"],
            ['name' => "Empresas de Soluciones Tecnológicas"],
            ['name' => "Tiendas de Material de Construcción"],
            ['name' => "Escuelas de Música"],
            ['name' => "Servicios de Revisión de Documentos"],
            ['name' => "Talleres de Fotografía"],
            ['name' => "Empresas de Transporte de Mercancías"],
            ['name' => "Servicios de Reparación de Electrodomésticos"],
            ['name' => "Tiendas de Ropa para Deportes Extremos"],
            ['name' => "Empresas de Planificación Financiera"],
            ['name' => "Centros de Enseñanza en Línea"],
            ['name' => "Servicios de Desarrollo de Aplicaciones"],
            ['name' => "Agencias de Diseño Web"],
            ['name' => "Servicios de Capacitación en TI"],
            ['name' => "Tiendas de Ropa de Temporada"],
            ['name' => "Empresas de Producción de Videos"],
            ['name' => "Talleres de Escultura"],
            ['name' => "Centros de Formación en Habilidades Blandas"],
            ['name' => "Tiendas de Ropa de Alta Costura"],
            ['name' => "Empresas de Renovación de Oficinas"],
            ['name' => "Servicios de Gestión de Proyectos Digitales"],
            ['name' => "Escuelas de Deportes"],
            ['name' => "Tiendas de Equipos de Seguridad"],
            ['name' => "Empresas de Consultoría en Gestión"],
            ['name' => "Servicios de Marketing para Redes Sociales"],
            ['name' => "Tiendas de Productos de Belleza Natural"],
            ['name' => "Empresas de Asesoría Jurídica"],
            ['name' => "Talleres de Fotografía Profesional"],
            ['name' => "Tiendas de Juegos de Mesa"],
            ['name' => "Empresas de Desarrollo de Aplicaciones Móviles"],
            ['name' => "Servicios de Edición de Fotos"],
            ['name' => "Consultorías en Estrategia de Negocios"],
            ['name' => "Tiendas de Ropa para Eventos Especiales"],
            ['name' => "Centros de Investigación y Desarrollo"],
            ['name' => "Servicios de Instalación de Redes"],
            ['name' => "Tiendas de Artículos de Oficina"],
            ['name' => "Empresas de Servicios de TI"],
            ['name' => "Talleres de Pintura"],
            ['name' => "Servicios de Gestión de Contenidos"],
            ['name' => "Tiendas de Productos para el Cuidado del Cabello"],
            ['name' => "Consultorías en Tecnología"],
            ['name' => "Empresas de Eventos Corporativos"],
            ['name' => "Servicios de Diseño de Logos"],
            ['name' => "Tiendas de Decoración Temática"],
            ['name' => "Talleres de Artes Marciales"],
            ['name' => "Tiendas de Equipos de Audio"],
            ['name' => "Servicios de Gestión de Redes Sociales"],
            ['name' => "Empresas de Auditoría"],
            ['name' => "Tiendas de Material de Arte"],
            ['name' => "Servicios de Diseño Editorial"],
            ['name' => "Consultorías en Innovación"],
            ['name' => "Empresas de Servicios de Consultoría"],
            ['name' => "Tiendas de Artículos de Regalo"],
            ['name' => "Servicios de Traducción Técnica"],
            ['name' => "Talleres de Creación de Contenidos"],
            ['name' => "Tiendas de Productos para el Hogar Inteligente"],
            ['name' => "Servicios de Gestión de Campañas Publicitarias"],
            ['name' => "Empresas de Consultoría en Recursos Humanos"],
            ['name' => "Tiendas de Artículos de Cocina Gourmet"],
            ['name' => "Servicios de Fotografía Corporativa"],
            ['name' => "Empresas de Desarrollo de Juegos"],
            ['name' => "Talleres de Escritura Creativa"],
            ['name' => "Tiendas de Accesorios para Deportes"],
            ['name' => "Servicios de Instalación de Software"],
            ['name' => "Consultorías en Estrategia Digital"],
            ['name' => "Tiendas de Productos de Limpieza"],
            ['name' => "Servicios de Organización de Espacios"],
            ['name' => "Talleres de Diseño de Interiores"],
            ['name' => "Tiendas de Productos para el Bienestar"]
        ];
        
        DB::table('types')->insert($types);
    }
}
